### PR TITLE
Fix Air Quality with Météo-France + update French names for indexes as per the latest ATMO European specification

### PR DESCRIPTION
**Pull request by papjul**
- Concentration is now displayed (highest value for the day, or mean value for PM 2.5 and PM 10)
- IQA index in Europe is not a value but a word, so putting an arbitrary value equal to AirQuality.AQI_INDEX_X so it does display something
- Update French values as per ATMO specification for IQA index

### CODE REVIEW

**Comment by rthery** [comment]
@papjul This still only use Auvergne-Rhône-Alpes ATMO data right ?
I'm looking into adding support to national data from https://www.atmo-france.org/, what do you think is best, remove the AURA provider or keep it and use the France data for the rest of the country ?

**Comment by papjul** [comment]
That's right, what makes it difficult is that you need a provider that supports lon and lat as parameters (and not a postal code which are not really reliable).

Also, they don't all support the same data (hourly pollutants for example).

I had a quick look and didn't find anything easy to implement but I didn't know there was a national API. Let me know what you can find!

Side note: the national API says you must refresh only once a day (maybe we should implement #244 first).

**Comment by rthery** [comment]
Thanks! I'll try to check if we can use lon and lat values for that API then, they seem to support some complex search filters

**Comment by papjul** [comment]
Replaced by #440

**Pull request closed without merging**
