### PR TITLE
Add Gadgetbridge support: fix #237 

### LINKED ISSUE #237: [Feature Request] Gadgetbridge TinyForecastGermany/WeatherNotification receiver support
I'm a gadgetbridge user and don't want to use another application to get weather forecast on my device, so I think it would be good if there will be support for weather forecast for gadgetbridge.
Source code of TinyForecastGermany receiver is located [here](https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/externalevents/TinyWeatherForecastGermanyReceiver.java)

### PR DESCRIPTION
**Pull request by NekoGirlSAIKOU**
Fix #237 
Gadgetbridge is an Android (4.4+) application which will allow you to use your Pebble, Mi Band, Amazfit Bip and HPlus device (and more) without the vendor's closed source application and without the need to create an account and transmit any of your data to the vendor's servers.
Gadgetbridge offers support for forwarding weather information to the band/watch and it needs the help of a weather provider. This PR makes GeometricWeather a weather provider.

### CODE REVIEW

**Comment by NekoGirlSAIKOU** [comment]
Just notice that Gadgetbridge uses AGPL so maybe I shouldn't directly use its WeatherSpec.java.
Maybe someday I will rewrite WeatherSpec.java and reopen this PR.

**Comment by 7ff04da4aa6ac37197e249299066ac30** [comment]
Any update on this? I'd very much like to have Geometric Weather be a weather provider for Gadgetbridge.

**Comment by NekoGirlSAIKOU** [comment]
> Any update on this? I'd very much like to have Geometric Weather be a weather provider for Gadgetbridge.

After open this PR I suddenly realized that Gadgetbridge uses AGPL while Geometric Weather uses LGPL so I can't use Gadgetbridge's code here. But to send weather information to Gadgetbridge `WeatherSpec.java` is necessary. Since it is `Parcelable` I think it hard to write different code providing same function. Maybe I would write almost the same code even if I haven't read it. So I have to close this PR.

**Comment by coxackie** [comment]
@NekoGirlSAIKOU I have opened a [ticket](https://github.com/TylerWilliamson/QuickWeather/issues/38) at `QuickWeather`, which is a very nice little weather app that seems to not have the licencing issues here. Just for your info, in case you want to port your effort there, so it does not go to waste.

**Pull request closed without merging**
