### PR TITLE
[MF] Fix crash if API gives us null for temperature

### PR DESCRIPTION
**Pull request by papjul**
Sorry for missing this one when fixing other issues.

Additionally, would it be possible to make the temperature @Nullable?
For forecast in 15 days, sometimes the min or max temperature is missing so I put 0 degrees instead as a workaround, but it's wrong...

### CODE REVIEW

**Comment by RemyL** [comment]
If i may particiape on this. First i don't understand how it's possible to get a null value ?
In a second time, it may be better to use an impossible value like 100 instead of 0 because it's possible for temperature to be 0

**Comment by papjul** [comment]
It's what Météo France provides as data.
I only saw the issue on "max" temperature of the last forecast day (in 15 days) so far.
On their website, when the temperature is null, it’s shown as -

Since it's max temperature, unless you live in a very cold city, max will pass under the min value, obviously showing it's a wrong value. Best would be indeed to not show this value at all, which is what I asked for in my first comment.
Putting 100 degrees is not a good idea, as it would completely ruin the graph scale for the other days.

**Comment by RemyL** [comment]
> It's what Météo France provides as data.
> I only saw the issue on "max" temperature of the last forecast day (in 15 days) so far.
> On their website, when the temperature is null, it’s shown as -
> 
> Since it's max temperature, unless you live in a very cold city, max will pass under the min value, obviously showing it's a wrong value. Best would be indeed to not show this value at all, which is what I asked for in my first comment.
> Putting 100 degrees is not a good idea, as it would completely ruin the graph scale for the other days.

Ok right, it's a good solution then

**Comment by WangDaYeeeeee** [comment]
The nullable value of temperature is indeed a tricky problem. Because once the null value is allowed, we need to make corresponding adaptions in other places, such as the trending view of the main interface.

If the null value will only appear on the last forecast day, is it possible not to provide the daily forecast for the last day?

**Comment by RemyL** [comment]
That's also what i was thinking about, showing one less day or even more. Actually it shows 14 days but we all knows that those results are far from correct results.
Maybe keeping this commit and showing only 10 days can be a good solution

**Pull request merged**
