### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by papjul**
Better wording on some strings, thanks to @ldmpub

### CODE REVIEW

**Comment by RemyL** [comment]
Would it be possoble to also modify line 273:
  <string name="feedback_short_term_precipitation_alert">Des précipitations peuvent avoir lieu dans les heures à venir.</string>

I'm posting here as a comment because i don't know how to modify it. This sentence is too long (45 characters max) and is not entirely displayed in notification.

Here is one possibility: "Précipitations possibles à venir"

**Comment by papjul** [comment]
I don't think there is a hardcoded limit of 45 characters.
I could not test this but I think notification content can be expanded?
Anyway, I shortened the sentence to 49 characters which should be enough to understand what happens.

**Comment by RemyL** [comment]
> I don't think there is a hardcoded limit of 45 characters.
> I could not test this but I think notification content can be expanded?
> Anyway, I shortened the sentence to 49 characters which should be enough to understand what happens.

There is no limit indeed, the issue is that notification doesn't expend. So the sentence is shortened.

**Comment by RemyL** [comment]
> I don't think there is a hardcoded limit of 45 characters.
> I could not test this but I think notification content can be expanded?
> Anyway, I shortened the sentence to 49 characters which should be enough to understand what happens.

It was not enouth, the last letter is not displayed it's showing : "à veni...'
I'm not able to expend this notification and it doesn't seem to be on 2 lines

**Comment by papjul** [comment]
I said "enough to understand what happens", not "enough to show every character"

I think it is guessable what "veni" means (although I don't understand why it just doesn't show the last character instead of replacing it with "…"). I believe this limit differs from device width (some will be able to see the last character, some others will see less characters than this), chosen system font (some fonts are wider) and accessibility settings (DPI, zoom, etc), so I don't think this is something that absolutely need to be fixed in Geometric Weather for your specific device configuration, I think we can assume people will understand what the notification means even with some missing characters.

**Comment by RemyL** [comment]
> I said "enough to understand what happens", not "enough to show every character"
> 
> I think it is guessable what "veni" means (although I don't understand why it just doesn't show the last character instead of replacing it with "…"). I believe this limit differs from device width (some will be able to see the last character, some others will see less characters than this), chosen system font (some fonts are wider) and accessibility settings (DPI, zoom, etc), so I don't think this is something that absolutely need to be fixed in Geometric Weather for your specific device configuration, I think we can assume people will understand what the notification means even with some missing characters.

Right and i really didn't think abouth this dpi anything.
Anyway this is not important at all.

Moreother i didn't want to be rude or anything and in the contrary i thank both of you for all your work.
The app is really good now

**Pull request merged**
