### PR TITLE
Add F-Droid build flavor

### LINKED ISSUE #9: F-Droid
This app cannot be included into F-Droid due to binaries (liblocSDK7.so, BaiduLBS_Android.jar) with unclear license.
Is it possible to remove/replace them in some way?

### PR DESCRIPTION
**Pull request by dimqua**
Fixes #9.

Please note that automatic location detection is not available in 'fdroid' build flavor and location should be specified by user manually.

### CODE REVIEW

**Comment by moriel5** [comment]
I second this request, and although I would prefer to use Dark Sky (since they are one of the few services to get my location right), I think that OpenStreetWeather (I personally stay away from them, due to them being rather unreceptive when I had tried to help in regards to the area I live in) should also be a choice for a weather provider, and Open Street Maps should also be a choice for a location provider.

**Comment by picsi** [comment]
It might be worth taking a look at the conflicts.

**Comment by lionirdeadman** [comment]
@dimqua Is there any reason why you closed this?

**Comment by dimqua** [comment]
It is not relevant anymore, but now it much harder to add and maintain FOSS build flavor than a year ago. And since the upstream is not interested in it anyway, I decided to just close this PR.

**Comment by lionirdeadman** [comment]
I see :/

**Comment by Olika120** [comment]
Could this be merged? We(the users) really need a fully FOSS version of the app for privacy purposes.

**Comment by dimqua** [comment]
Since Native API support has been added as an option, now we can have location support in F-Droid version.

**Comment by Olika120** [comment]
Nice, now we just need a different build flavor without the proprietary services then

**Comment by dimqua** [comment]
I'm going to add it, but ATM I can't build the app: #64.

**Comment by Olika120** [comment]
I will try doing some fixes when i get home

**Pull request closed without merging**
