### PR TITLE
Add F-Droid build variant

### PR DESCRIPTION
**Pull request by papjul**
Solves #9 

In Android studio, you can now choose your build variant (bottom left of the editor):
- fdroid (debug or release). Does not contain any closed source code.
- gplay (debug or release). Same app as currently built.

This is how it works:
Under src/ directory, there are three directories:
- main is the code similar in both flavors
- fdroid contains code specific to F-Droid flavor. Basically, classes relying on closed source are replaced with stubs. However, there should actually never be used because preferences screen has been refactored to ignore closed source weather providers in preference settings when building the fdroid flavor. Only exception: Android Native Location provider was rewritten to remove GMS dependency.
- gplay contains code that does not match F-Droid inclusion criteria. Files in this directory are the same as in current master.

This patch was originally written by @mbestavros in a fork which I adapted to work as a "build flavor" that can be built directly upstream.

Hopefully, this should work exactly like before if you choose the gplay build flavor, however feel free to let me know if you are running into troubles.

### CODE REVIEW

**Comment by mbestavros** [comment]
Hooray! 🎉 Really happy to see this being proposed upstream.

@IzzySoft If this does go through, my fork would likely not be necessary. What changes would need to happen on the F-Droid side to support this?

**Comment by IzzySoft** [comment]
Depends. Volume of my forehead is limited, so: what's the current status?

**Comment by papjul** [comment]
This patch is complete.
It removes the same things as @mbestavros fork; some things were handled differently, such as classes relying on closed sources dependencies replaced with stubs instead of being deleted, and weather provider list being filtered on runtime (no worries, even if someone was able to select a "closed source" provider, underneath it would be one of the stub classes extending the "default" open source class).

What is different:
- Since we are upstream, the applicationId was kept intact. This implies if it is included on F-Droid, we would have to deprecate the old different applicationId in favor of the upstream package. I saw this use case (change of applicationId) on other F-Droid packages, I don't think it should be too much of a problem.
- The F-Droid build script needs to be edited slightly. We need to indicate that we are building the "fdroid" variant, and for paranoid purposes, rm the libs/ directory (although in the current state of things, this directory is never included when building). You can have a look at the OsmAnd build script for this.

Of course, this will be possible only if:
1. This pull request is merged
2. A new release is tagged

**Comment by IzzySoft** [comment]
Thanks for the nice summing-up, @papjul! As the packageId changes ("we would have to deprecate the old different applicationId in favor of the upstream package"), this would be handled as a "new app". I'd suggest to open an [RFP](https://gitlab.com/fdroid/rfp/issues) or, as the app basically is already available at F-Droid, go straight for a [merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/). You could use the YAML of @mbestavros' fork as a base, adjusting everything to your app, removing all existing build blocks and just place the one for your latest release in.

Once your app is listed, I'd suggest @mbestavros adds a note to the description of his app (and maybe also the Readme of his repo) informing existing users about the move. Let's give that a month or so to settle, then the fork could be "archived" (here at Github) to underline that it's no longer followed.

Does that sound reasonable?

**Comment by mbestavros** [comment]
@IzzySoft Yes, all that sounds reasonable to me!

I will probably hold off on making changes until upstream accepts this patch, of course. But after that, let's get the ball rolling. Given how long the process took last time, we should start ASAP.

**Comment by papjul** [comment]
Yes, let's do it like this ;)

Regarding RFP, I believe you can reopen https://gitlab.com/fdroid/rfp/-/issues/22 to avoid duplicates. I believe we should wait for patch merge before commenting there.

**Comment by IzzySoft** [comment]
You can reuse that RFP, or open a new one – as you feel best suited. And thanks for picking up!

**Comment by papjul** [comment]
Due to major changes, PR was rebased on #180 

Closing this one.

**Pull request closed without merging**
